### ISSUE TITLE
SVG problems

### ISSUE THREAD

**Issue by verajpatel** [verajpatel/svg-icon-sets#1]
My SVG's aren't loading onto the website. @charlie-quinn

**Comment by charlie-quinn** [comment]
In order for your icons to appear correctly, you'll need to export them again. Download the .AI file again and rewatch [this video](https://www.youtube.com/watch?v=NI-qGP5m-6M&list=PLWjCJDeWfDdeYtU0NMvYvfqqFA1Jsh3NM&index=14).

Follow this code structure to build out each block inside of the `<section>` container:
### HTML:
  `<section class="section section-bright gutter pad-t-2 pad-b-2">`
    `<h2 class="zetta text-center push-2">Mars colonization structures</h2>`
   `<div class="grid grid-stretch">`

      <div class="section-unit unit [ xs-1 s-1 m-1 l-1-3 ] gutter pad-t pad-b unit-content-distribute">
        <div class="max-length unit-content-distribute content-stretch">
          <i class="icon i-192 block center-block push">
            <svg><use xlink:href="images/space-icons.svg#space-bubbles"/></svg>
          </i>
          <h3 class="peta push-1-2">Space bubbles</h3>
          <p class="push content-stretch">Space bubbled buildings will house large green houses and natural habitats so Earth-borne life can live on Mars.</p>
          <div><a class="btn btn-ghost" href="#">Learn about space bubbles</a></div>
        </div>
      </div>
---
### STYLING:
_**(this is how we'll create the container's background color)**_
`.section-bright {
  background-color: #ff9500;
  background-image: linear-gradient(to bottom, #ff9500, #ff5e3a);
  color: #fff;
}`

**_(we'll give each block/unit a border-bottom with an opacity of 30%)_**
`.section-unit {
  border-bottom: 3px solid rgba(255, 255, 255, .3);
}`

_**(we'll target the last block/unit and remove the border-bottom from it)**_
`.section-unit:last-child {
  border-bottom-color: transparent;
}`

**_(we'll style out borders for large screens using a media querie)_**
`@media only screen and (min-width: 60em) {`

  `.section-unit {
    border-bottom: 0;
    border-right: 3px solid rgba(255, 255, 255, .3);
  }`

  `.section-unit:last-child {
    border-right-color: transparent;
  }`

`}`

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
